name: Pipeline

on:
  push:
    branches:
      - ci/cd

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t lramon2001/trimnet_drug:1.0.0 .

      - name: Log into Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN}} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        
      - name: Push Docker Image to Docker Hub
        run: docker push lramon2001/trimnet_drug:1.0.0
        
  test:
    needs: build
    runs-on : ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2


      - name: test-envoriment
        run: pip3 install pytest

      - name: test
        run: pytest

  lint:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: pip install flake8

      - name: Lint with flake8
        run: flake8 ./trimnet_drug

  documentation:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Sphinx
        run: pip install sphinx

      - name: Create Source Directory
        run: mkdir -p docs/source

      - name: Create index.rst
        run: echo "Welcome to My Project Documentation!" > docs/source/index.rst

      - name: Generate Documentation
        run: |
          sphinx-build -b html /home/runner/work/TrimNet/TrimNet/docs/source /home/runner/work/TrimNet/TrimNet/trimnet_drug/docs/build/html
        working-directory: ./trimnet_drug

      - name: Upload Documentation
        uses: actions/upload-artifact@v2
        with:
          name: Documentation
          path: ./trimnet_drug/docs/build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./trimnet_drug/docs/build/html

  deploy:
    needs: documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Dependencies
      run: ls && pip install -r requirements.txt

    - name: Update Version
      run:  python3 update_versioning.py
    - name: Build and Upload Package to PyPI
      run: |
        pip install setuptools
        pip install wheel
        python setup.py sdist bdist_wheel
        pip install twine
        twine upload --username $TWINE_USERNAME --password $TWINE_PASSWORD dist/*
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}




